// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy9AN8e0vh7fJRwtG8_5YKhMh1YkO0xzQ',
    appId: '1:397827443104:web:ff7da46ad57ee2f23abcc5',
    messagingSenderId: '397827443104',
    projectId: 'expensemaster-19ec1',
    authDomain: 'expensemaster-19ec1.firebaseapp.com',
    storageBucket: 'expensemaster-19ec1.appspot.com',
    measurementId: 'G-0TRWJ0PXKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAncic_QmTk0GhfJgqjLJw7l9Km1TTnyFI',
    appId: '1:397827443104:android:1dcff30b7b60cdc43abcc5',
    messagingSenderId: '397827443104',
    projectId: 'expensemaster-19ec1',
    storageBucket: 'expensemaster-19ec1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnizyTrzk57tswQlxKCUl8rvsLQq378Yk',
    appId: '1:397827443104:ios:c98059601dc164433abcc5',
    messagingSenderId: '397827443104',
    projectId: 'expensemaster-19ec1',
    storageBucket: 'expensemaster-19ec1.appspot.com',
    iosBundleId: 'com.example.expenseMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnizyTrzk57tswQlxKCUl8rvsLQq378Yk',
    appId: '1:397827443104:ios:609892c49c991dd03abcc5',
    messagingSenderId: '397827443104',
    projectId: 'expensemaster-19ec1',
    storageBucket: 'expensemaster-19ec1.appspot.com',
    iosBundleId: 'com.example.expenseMaster.RunnerTests',
  );
}
